[server]
port = 7860
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
headless = true
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#0284c7"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#0f172a"
font = "sans serif"

